---
title: "PSC 663 (PhD): The Politics of Foreign Aid"
subtitle: "Wednesdays, 1:00-3:30pm"
author: "Instructor: Dr. Amanda B. Edgell (abedgell@ua.edu)"
date: "Fall 2023"
output: 
  html_document:
   toc: true
   toc_float: true
---


```{css, echo=FALSE}
p {
  font-size: 16px;
}

td {
  font-size: 16px;
}

ul li{
 font-size:16px;
}

ol li{
 font-size:16px;
}
```


**Office Hours:** 314 TH, Tuesdays, 3:45-4:45pm

**Last Updated:** `r format(Sys.time(), '%d %B, %Y')`



---  
  
# Course Description {#description}
  
Since the end of WWII, donor countries have spent over $7 trillion on foreign aid. Many of these projects seek to enhance human well-being through improved infrastructure, access to food, education opportunities, healthcare provision, broadened political freedoms, and increased security. Yet, the decisions behind when, where, and how to allocate foreign aid are embedded in domestic and international power dynamics. Donor countries make strategic choices about which countries to assist and which target areas to prioritize. Likewise, recipient governments have their own agendas and engage in strategies to capture foreign aid. This course examines these dynamics, with a particular emphasis on how the United States government makes foreign aid decisions. By the end of the semester, you will have foundational working knowledge that you can apply throughout your career in public service, academia, or the private sector.

---  
  
# Student Learning Objectives {#slos}
 
By the end of the semester, you should be able to... 

1. Understand the evolution and goals of U.S. foreign aid policy
2. Explain the political economy dynamics of development assistance
3. Develop a research paper addressing an empirical puzzle related to U.S. foreign aid decisions or administration

---  
  
# Required Texts{#texts}

* Norris, John. 2021. *The Enduring Struggle: The History of the U.S. Agency for International Development and America's Uneasy Transformation of the World.* New York: Roman & Littlefield.
* Patterson, Amy S. 2018. *Africa and Global Health Governance: Domestic Politics and International Structures.* Baltimore, MD: Johns Hopkins University Press. Free access here: https://muse.jhu.edu/book/57836.
* Bush, Sarah Sunn. 2015. *The Taming of Democracy Assistance: Why Democracy Promotion Does Not Confront Dictators* New York: Cambridge University Press. 


---  

# Pre-requisites
Admission into the PhD program and permission from the PPA faculty  

---  


# Course Requirements



## 1. Participation (20\%) {#discussion}

You are expected to attend and participate in all scheduled class meetings. You should arrive on time and be prepared to discuss the assigned material. This means that you need to actively engage with the required readings before class, asking questions such as:

* What *type* of material is this (i.e. scholarly research, policy paper, editorial)?
* What is the *question* or problem motivating this work? 
* What *methods* do the author(s) use? 
* What are the *conclusions* or main arguments? 
* How does this work *relate* to other materials we've discussed in class? 
* What are the core *contributions* and *limitations* of this work? 
  
I strongly encourage you to prepare notes on the readings and bring them to class. 

For each class session, you can earn up to five points toward your participation grade. To earn points, you must actively participate in the discussion. You will not earn participation credit for merely attending class. You may also lose participation credit if you arrive to class late or if you are not actively listening to the discussion (e.g., working on other assignments, doom scrolling) since this is disrespectful and potentially distracting. It is possible to earn a negative participation credit score for the day.

## 2. Leading Class Discussion (30\%)

You will lead the class discussion on 13 September and another week of your choice. This assignment is intended to give you additional teaching experience, particularly at the graduate level. You should use about one hour to present the assigned readings using PowerPoint. Afterward, you will lead the other students in an activity designed to help the class better understand the material through active learning. For 13 September, Dr. Edgell will provide materials and instructions for the in-class activity. For the other week, you are responsible for developing the activity, in consultation with Dr. Edgell.    


## 3. Research Paper (50\%){#paper}

You will develop an original research project that investigates an empirical puzzle related to U.S. foreign aid decisions or administration. The project should thoroughly address the research question using qualitative, quantitative, or mixed methods. Your final paper and presentation should have a clearly articulated research question, review of relevant literature, preliminary theory, methodology, discussion of results, and conclusion. This is an opportunity to explore broader questions related to your possible dissertation research, for a conference paper, or article manuscript. To help you succeed at this assignment, we will have several meetings and interim deadlines to track your progress. These are summarized below.  




|  Assignment | Description            | Deadline     |   
| :-----------| :--------------------  | :------------|
| Meeting 1   | Meet with Dr. Edgell to discuss paper ideas | Wed, 06 Sep, 3:45-4:45pm |
| Project proposal and annotated bibliography | Prepare a 3-5 page proposal for your project and an annotated bibliography of sources you have found on the research topic/question     | Fri, 22 Sep, 11:59pm     |
| Meeting 2       | Meet with Dr. Edgell for feedback on proposal   |  Wed, 27 Sep, 3:45-4:45pm    |
| Early rough draft                  | This does not need to have all the content, but you should aim to have the literature review, theory, and methods written, plus an outline for other sections    | Fri, 27 Oct, 11:59pm    |
| Meeting 3     | Meet with Dr. Edgell to discuss progress and early rough draft     | Wed,  01 Nov, 3:45-4:45pm     |
| Final paper     | Your final paper should be around 7,000 to 10,000 words.     | Fri, 01 Dec, 11:59pm    | 
| Presentation | You will present your paper (no longer than 15 minutes) to the rest of the class for feedback and discussion | Wed, 06 Dec, 1-3:30pm




---  

# Attendance Policy {#excuses}

Students are expected to attend all scheduled class meetings. A student may miss class only for good cause and must provide written documentation in advance or within **48 hours** of the missed class or as soon as physically possible.

Good cause for missing class, subject to the professor's discretion, may include:

* Sickness that disables the student from attending class or poses a significant threat to the health of others
* Sickness of, or accident involving, a spouse or dependent, that requires the student to be with the spouse or dependent
* An accident that necessarily prevents the student’s attendance in class 
* The death of a family member or friend
* An interview for an internship or a permanent position after graduation, if the interview cannot reasonably be scheduled to avoid a conflict
* A meeting or event at which the student must appear as a representative of the University (including official athletic events)
* Comprehensive exams, where the department schedules these to take place on the same day, one day before, or one day after the class meeting
* Jury duty on the same day as the class meeting
* Other good cause as is warranted under the circumstances 

Deadlines for other course assignments do not constitute a good cause for missing class. Extracurriculars (including Greek Life) are also only generally acceptable excuses for absences if the student is acting as an official representative of the University (e.g., mock trial tournaments and official athletic events).


## Excessive Absences ##

A student who is absent *for any reason* from the equivalent of three class meetings will only be allowed to continue with the course if they obtain approval from the professor. In such circumstances, the student will be marked as failing the course with an “F” letter grade unless they withdraw from the course before the final grading period.


--- 

# Grading Policies {#grades}


We will use the following grading scale in this class. Graduate students must maintain a 3.0 cumulative GPA or higher for all graduate coursework taken at the University of Alabama. A minimum 3.0 GPA is also required to be eligible for funding from the department.  

|      A (4.0)     |     B (3.0)      |       C (2.0)      |      F   (0.0)      |
| :---------: |  :-------:  |  :----------: |  :------------:| 
|  Exemplary  | Adequate    |  Inadequate   |  Insufficient  |
| 90-100\%    | 75-89\%     |  50-74\%      |  0-49\%        |


## Formatting and Citation Guidelines

The U.S. Agency for International Development provides a style guide for all materials it produces. The guide contains useful tips on how to prepare concisely written and well-formatted documents. It is your responsibility to familiarize yourself with these guidelines and follow them when preparing written reports for this class. The guide is available here: https://www.usaid.gov/sites/default/files/2022-05/USAID_Style_Guide_October_2021.pdf. 

We will use the Chicago Author-Date citation system, in line with the U.S. Agency for International Development's style manual. You can find the Chicago Author-Date style guide here: https://www.chicagomanualofstyle.org/tools_citationguide/citation-guide-2.html. 


## Missed Exams & Coursework {#late}

As a general rule, I do not accept late work. Deadlines on the [Course Schedule](schedule.html) are there to help ensure you successfully achieve the student learning objectives by the end of the semester. If you cannot meet a deadline or will need to miss an exam for a good cause, you must provide written documentation within  **48 hours** of the missed assignment or as soon as physically possible. 



## Grade Disputes {#disputes}

If you think I have made an error, contact me during office hours or schedule an appointment within one week of receiving the grade. Out of respect for your right to privacy under the University’s Confidentiality of Student Records policy and the Family Rights and Privacy Act of 1974, I do not discuss grades via email.



## Incomplete Grades {#incomplete}

Incomplete “I” grades will be recorded only in exceptional cases when: the student (a) has completed a substantial portion of the course and is otherwise passing, (b) is unable to complete a well-defined portion of a course for reasons beyond the student’s control, and (c) in the instructor’s judgment  can complete the required work without repeating the course. 

The University of Alabama policy requires all grades of “I” to be removed no later than 12 months after the end of the term in which they were awarded but prior to the student’s graduation or the grade of “I” will be changed to an “F.” The “I” may not be used as a means to re-enroll in a course during a subsequent semester. A grade of “I” may not be used to satisfy a prerequisite requirement.

Requests for "I" grades must be submitted in writing to the instructor using this form: https://forms.gle/JWRZz87gmhyLmBdr9. Such requests can be sent no earlier than 01 November 2023 (the last day to drop a course with a "W") and no later than 3:30pm on 06 December 2023 (the end of our last class session). 

--- 

# Plagiarism and AI Technology

Learning to communicate your ideas effectively is an essential skill for any career path you may eventually take after graduation. While AI technology is exciting and offers opportunities to improve the efficiency of our research and writing, misusing this technology has negative consequences. Bots like ChatGPT are only accurate about 60-70% of the time and have been known to fabricate information. Using these tools to write your work for you is not only unethical, it renders you invisible. Your voice matters! Don’t let an AI silence you.

In line with UA’s Academic Misconduct policy, I expect you to generate your own work in this course. By submitting an assignment, you claim this work is entirely your own. Any work that you have paraphrased should be correctly cited. If you use more than three words in a row from someone else’s work, use quotation marks and cite the source, including the page number. 

If you submit work generated by someone else or created by a computer application such as ChatGPT, this will be considered a violation of the Academic Misconduct policy and may be reported to the Department Chair or Dean’s office for review.

You may use word processing tools to check your spelling and grammar and assist with simple re-phrasing tasks. For example, I use the Grammarly application to help with my writing. It checks spelling and punctuation and sometimes provides advice on rephrasing sentences for clarity. This is a perfectly acceptable use of technology. However, having Grammarly’s AI assistant or similar tools write your work for you is unacceptable.


---  

# Controversial Topics

Some of the topics in this course may be considered controversial. One of the core purposes of a university is to discuss important topics through a scholarly lens. When members of a class find themselves feeling strongly about a topic, that is a signal that the topic is important enough to be discussed rather than avoided. Differences of opinion are expected and will result in rich discussions. In these discussions students will be expected to demonstrate a thorough understanding of concepts presented in the course materials and to ground their positions in concepts and evidence relevant to the course. This in turn will entail coming to class prepared, asking relevant questions, sharing perspectives, having a willingness to listen, and practicing open-mindedness when encountering the perspectives of others. In this course we will assume the positive intentions of all class members when discussing important topics, and we will give them the benefit of the doubt when considering their perspectives and sharing our own. 

---  

# Other Policies

## Names and Pronouns 

UA provides instructors with a roster listing each student’s legal name. However, I will gladly honor your request to address you by an alternate name or gender pronoun. Please advise me accordingly early in the semester so that I may make appropriate changes to my records. You can also designate your pronouns in Banner.



## TurnItin Policy

Students agree that their enrollment in this course allows the instructor the right to use electronic devices to help prevent plagiarism. All course materials are subject to submission to Turnitin.com for the purpose of detecting textual similarities and plagiarism. 



## Audio/Video Recordings

This is an in-person discussion-based seminar. Therefore, as a general rule, no one is allowed to make audio or video recordings of our class sessions. This will facilitate an active, honest, open discussion during our meetings.  Any student violating this rule may be referred to the Office of Student Conduct for disciplinary action. Students with documented disabilities requiring access to audio recordings of missed classes should notify me formally through the ODS portal so that we can make alternative accommodations that are more reasonable for the course format.



## Sharing Course Materials

All course materials, presentations, and class discussions are only for viewing by members of this class section. They may not be posted in any public forum or shared with anyone not enrolled. Any student violating these rules may be referred to the Office of Student Conduct for disciplinary action.


## Academic Misconduct 

Students are expected to be familiar with and adhere to the official Academic Misconduct Policy provided in the Online Catalog. Any suspected academic misconduct, including plagiarism, will be referred to the College of Arts & Sciences Dean’s Office.  For more information: https://provost.ua.edu/academic-misconduct/ 
 

## Disability Accommodations

The University of Alabama is committed to ensuring the full participation of all students in its programs. If you have a documented disability (or think you may have a disability) and need reasonable accommodation(s) to participate in this class, contact the Office of Disability Services (or ODS; 205-348-4285, ods@ua.edu, Houser Hall 1000, www.ods.ua.edu) as soon as possible. If you have been approved to receive accommodations through ODS, please meet with your instructor or College designee during office hours or by appointment to review your accommodation letter and discuss how accommodations can be implemented in this course.




## Pregnancy Accommodations

Title IX protects against discrimination related to pregnancy or parental status. If you are pregnant and will need  accommodations for this class, please review the University’s FAQs on the UAct website: https://uact.ua.edu/information/pregnancy. 




## Religious Observances

Under the Guidelines for Religious Holiday Observances, students should notify the instructor in writing or via email during the first two weeks of the semester of their intention to be absent from class for religious observance. The instructor will work to provide reasonable opportunity to complete academic responsibilities as long as that does not interfere with the academic integrity of the course. See full guidelines at Religious Holiday Observances Guidelines: https://provost.ua.edu/oaa-guidelines-for-religious-holidays-observance/ 




## UAct Ethical Community 

The University of Alabama is committed to an ethical, inclusive community defined by respect and civility. The UAct website (http://www.ua.edu/uact) provides extensive information on how to report or obtain assistance with a variety of issues, including issues related to dating violence, domestic violence, stalking, sexual assault, sexual violence or other Title IX violations, illegal discrimination, harassment, hate or bias incidents, child abuse or neglect, hazing, threat assessment, retaliation, and ethical violations or fraud.




## Severe Weather Protocol

The guiding principle at The University of Alabama is to promote the personal safety of our students, faculty, and staff during severe weather events. Please see the latest severe weather guidelines in the Online Catalog: www.ready.ua.edu/severe-weather-guidelines/. In particular, I recommend downloading the ABC-3340 weather app, following James Spann on social media, and activating emergency alerts on your mobile devices.




## Mandatory Reporting

As a faculty member at the University of Alabama, I am a mandatory reporter for known or suspected child abuse or neglect. This means that if I become aware of harm or threatened harm, sexual abuse, sexual exploitation, or negligent treatment of any person under the age of 18 or under the age of 19 in need of protective services, I must immediately report the suspected abuse to the University of Alabama Police Department. For more information:  https://uact.ua.edu/information/child-protection 



## Responsible Reporting

As a faculty member at the University of Alabama, I am considered a responsible reporting individual for sexual misconduct under Title IX regulations. This means that I am required to immediately report known incidents of sexual harassment, sexual assault, dating/domestic violence, and stalking to the Title IX Coordinator and the Designated Harassment Resource Person under the UAct program. For more information: https://uact.ua.edu/information/titleix 

---


# Wellness Resources 

College can be a stressful time.

If you or someone you know is facing a challenging time or dealing with academic or personal stress, anxiety, depression, or other concerns, we strongly encourage and support you to seek assistance or to help friends find the care that they may need. Please refer to our Campus Resource List for Students: https://alabama.box.com/s/nz3gs827kx538255typ9hm5owd7x0yj8.

Also, If you are experiencing a personal crisis and need urgent assistance, you can also contact the following resources:

*Counseling Center*

Monday-Friday during routine Center hours (205-348-3863).
Weekends, holidays, after-hours (contact UAPD at 205-348-5454 and ask to speak with the on-call counselor).
You may also text BAMA to 741-741 to text with a trained volunteer.
Women and Gender Resource Center

Monday-Friday during routine Center hours (205-348-5040).
Weekends, holidays, after-hours (contact UAPD at 205-348-5454 and ask to speak to the on-call advocate for the WGRC.


---



# Notification of Changes

The instructor reserves the right to amend this document as the need arises. In such instances, students will receive notification in class and via email with reasonable time to adjust to any changes. The most recent version of the syllabus can be found on the course website: https://abedgell.github.io/psc663.

---



